name: CI (CMake + Unity + FFF + STM32)

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  unit-tests:
    name: Host Unit Tests (Unity + FFF)
    runs-on: ubuntu-latest

    container:
      image: javibajocero/stm32cubeclt-builder:1.19.0 # has arm tools

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure (host tests)
        run: |
          cmake -S . -B build-host \
            -G Ninja \
            -DUNIT_TEST=ON \
            -DUNIT_COVERAGE=ON
          # NOTE:
          #  -DUNIT_TEST toggles your CMake to build the unit test executable(s)
          #  -DUNIT_COVERAGE should add --coverage or -fprofile-arcs -ftest-coverage to C/CXX/LD flags

      - name: Build unit tests
        run: cmake --build build-host --config Debug --target unit_tests -j

      - name: Run tests (CTest)
        run: ctest --test-dir build-host --output-on-failure

      - name: Coverage (gcovr)
        if: always()
        run: |
          gcovr -r . build-host \
            --xml-pretty --xml coverage.xml \
            --html-details coverage.html \
            --exclude '.*third_party/.*' \
            --exclude '.*tests/.*'
          echo "Coverage report generated."

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-host
          path: |
            coverage.html
            coverage.xml

  firmware-build:
    name: STM32 Cross Build (arm-none-eabi)
    runs-on: ubuntu-latest

    container:
      image: javibajocero/stm32cubeclt-builder:1.19.0 # has arm tools
      
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build firmware
        run: |
          echo "🔧 Building firmware..."
          # Remove existing build directory (clean start)
          rm -rf build

          # Generate Makefiles
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -B build --clean-first

          # Clean and build
          cd build
          make clean
          make -j$(nproc)  # builds with all CPU cores
          ls
          cd ..


      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${CMAKE_PROJECT_NAME}
          path: artifacts
